#! /usr/bin/env bash
set -euo pipefail

: "${GO:=go}"
: "${VERSION:=}"

if [[ -z "${VERSION}" ]]; then
   VERSION=$(git describe --tags --always --abbrev=4 --dirty)
fi


arch=amd64
for os in linux freebsd openbsd darwin; do
    target=bin/shuttermint-${os}-${arch}-${VERSION}
    echo "Building ${target}"
    env GOARCH=${arch} GOOS=${os} ${GO} build -o ${target} -ldflags "-X github.com/brainbot-com/shutter/shuttermint/cmd/shversion.Version=${VERSION}" .
done
