// Code generated by "stringer -type=phase"; DO NOT EDIT.

package puredkg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Off-0]
	_ = x[Dealing-1]
	_ = x[Accusing-2]
	_ = x[Apologizing-3]
	_ = x[Finalized-4]
}

const _phase_name = "OffDealingAccusingApologizingFinalized"

var _phase_index = [...]uint8{0, 3, 10, 18, 29, 38}

func (i phase) String() string {
	if i < 0 || i >= phase(len(_phase_index)-1) {
		return "phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _phase_name[_phase_index[i]:_phase_index[i+1]]
}
