// Code generated by "stringer -type=Phase"; DO NOT EDIT.

package puredkg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Off-0]
	_ = x[Dealing-1]
	_ = x[Accusing-2]
	_ = x[Apologizing-3]
	_ = x[Finalized-4]
}

const _Phase_name = "OffDealingAccusingApologizingFinalized"

var _Phase_index = [...]uint8{0, 3, 10, 18, 29, 38}

func (i Phase) String() string {
	if i < 0 || i >= Phase(len(_Phase_index)-1) {
		return "Phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Phase_name[_Phase_index[i]:_Phase_index[i+1]]
}
