#!/usr/bin/env python3

# workaround https://github.com/eth-brownie/brownie/issues/873

import re
import sys

from brownie.project.compiler import solidity
from brownie._cli.__main__ import main

def _generate_coverage_data(*args, **kwargs):
    return {}, {}, {}
solidity._generate_coverage_data = _generate_coverage_data


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
